### ISSUE TITLE
Missing package on install: dialog and grub-install not found issues

### ISSUE THREAD

**Issue by negativeExponent** [void-linux/void-mklive#135]
Using the latest commit, created the iso on a uefi machine. when starting to install using void-installer on cmd, dialog package was missing. also grub-install was not found during the grub setup portion.

**Comment by bobertlo** [comment]
I could be wrong but looking briefly I think the installer target is used to create the canonical install images while mklive is more of a starting point that you can add packages to?

Anyone feel free to correct me if I am wrong. I have run into this in the past and just finally read the scripts to try to figure it out :)

**Comment by bobertlo** [comment]
So, with some help we have tracked down the canonical build mechanism:

https://github.com/void-linux/void-mklive/blob/master/build-x86-images.sh.in

It would be nice if maybe the base packages could be moved into this repository somehow? Or at least documented. I'll look into that if noone objects.

**Comment by the-maldridge** [comment]
mklive is the most minimal setup of void that will boot. if you want a release ISO, use the script mentioned above.

**Comment by negativeExponent** [comment]
i dont get it then. why have a script then on the final iso that is just incomplete. missing grub-install is being part of a "minimal" setup? yeah, you can add what you want, and even do the install purely by hand fine. but that is not the point. Looks like void never changed since the last time i used it last year.

**Comment by bobertlo** [comment]
I would like to propose we make one of the following changes (we being myself if it is welcome):

1. Modify mklive.sh to not include the installer script by default, since it will not work without these dependencies. Then add a flag (say `-i`) that adds the installer and the minimal packages from the infrastructure scripts. The infrastructure scripts would have to add this flag, but nothing else would change.

2. Modify mklive.sh to include these packages by default so that the installer is functional. Users could still override with `-p ""` for the bare minimum, and `-p` would override this variable and nothing would change downstream in the infrastructure scripts.

3. Add to the README that the distributed base live image includes the packages `grub-i386-efi`, `grub-x86_64-efi`, `dialog`, which are required for the install script to function, as well as `cryptsetup`, `lvm2`, and  `mdadm`, which are convenient for certain setups. The other live images have more packages included, which can be found at [mentioned script] if they want more information about the load-out of those variants.

I think `3.` would be useful even if we do `1.` or `2.`. I will draft a PR somewhere along these lines at some point if there are no objections brought up.

**Comment by ericonr** [comment]
> Modify mklive.sh to not include the installer script by default, since it will not work without these dependencies. 

I like this one!
