### ISSUE TITLE
Live installer graphics failure

### ISSUE THREAD

**Issue by brho** [void-linux/void-mklive#160]
The void installer (void-live-x86_64-20191109-enlightenment.iso) has graphical bits that failed on my desktop/monitor.  After selecting either entry from Grub (void or void RAM), about 2/3 of my screen was the void graphic, and the lower third was pixelated error messages.  The errors looked like nouveau timeouts.  The lower 1/3 was the output of the console, but with some weird line wrapping too.  If I hit enter a bunch, eventually I'd see new 'text' there.

To get the thing working at all, I had to hack the grub command line, set gfxpayload=keep and pass nomodeset to linux, and stripped out the vconsole args (probably needlessly).  

At that point, I could at least get to a working terminal, however every 5 seconds or so the console would switch to the 'X' console (F7), and I'd have to ctl-shift-F1 back to my shell.  I managed to figure out that lxdm was part of the problem, so chmod -x /sbin/lxdm 'solved' the problem, at least for this boot.  I think runsv was starting it, it would take over the console, and possibly fail.

FWIW, I have an nvidia geforce RTX 2070 super (vendor 0x10de device 0x139e).  Perhaps the nouveau driver didn't like it?

Regardless of the root cause of my particular issue, I suggest having an *easy* option for users to fallback to a "no graphics whatsoever" mode for installation.  I imagine other users will have similar issues.

**Comment by pullmoll** [comment]
You basically have this using the `base` installer which does not have `X11` and does not even try to start a `DM`.
I agree, however, that a boot option to not try to start the `DM` (i.e. no-X11) might be useful even for the Live ISOs which have a DM/DE available.
If you know how to add that to the isolinux config perhaps create a PR for this addition?

**Comment by hippi777** [comment]
hi there! :)

maybe this could be interesting to u, maybe it can even help magically to make things smoother, however i dont have any experience with it as of now, and i didnt find it in the void repos:
https://github.com/Obsidian-StudiosInc/entrance

btw i didnt get such issues neither with the latest live, nor its installed version, so i guess u may be right about nouveau, and, fyi, i have integrated intel graphics if im right (asus s200e-ct206h). furthermore i have 3 problems with it on debian that i didnt have on void when i tried it, and i plan to use void with it, just i still need to arrive to that point... :D otherwise note that my latest experimenting took place some months ago, and theres some chance that anything happened in this period.

and finally, i guess this is actually an upstream issue, and in that case: https://phab.enlightenment.org

good luck! :)

**Comment by ericonr** [comment]
> If you know how to add that to the isolinux config perhaps create a PR for this additional option for the boot menu?

We could add a different services directory that isn't graphic, then boot with `nographics` in the kernel command line or similar. Because the other option is booting into `single`, and that one is too barebones.
