### ISSUE TITLE
mkplatformfs.sh complaints about ld-musl-aarch64.so.1 and creates a (broken) tarball anyway.

### ISSUE THREAD

**Issue by ftpd** [void-linux/void-mklive#210]
I'm trying to create musl image for my rPi 400 (the same hardware as rPi4).

The commands I'm using are:

```
./mkrootfs.sh aarch64-musl
./mkplatformfs.sh rpi4 void-aarch64-musl-ROOTFS-20210601.tar.xz
./mkimage.sh void-rpi4-PLATFORMFS-20210601.tar.xz
```

During `mkplatformfs` step I'm getting this error:

```
qemu-aarch64-static: /lib/ld-musl-aarch64.so.1: Invalid ELF image for this architecture
```

but it finishes anyway:

```
Running tar -cp --posix --xattrs -C /tmp/tmp.df1imP7XUF . | xz -T0 -9 > void-rpi4-PLATFORMFS-20210601.tar.xz
Successfully created void-rpi4-PLATFORMFS-20210601.tar.xz (rpi4)
```

The image can be flashed on SD card, but when I try to boot, It throws a few lines for a fraction of second (that's why I can't paste them here) and rPi turns itself off.

The same procedure for glibc image works flawlessly. I'm doing it from inside VM with Void (kernel 5.11.22) running on glibc. I even tried to spin a completely fresh VM with musl, but the same error.

What am I doing wrong?

**Comment by sammifammish** [comment]
ftpd helped me figure this out on IRC and I'm posting the answer here for posterity. The problem was that the mkplatformfs.sh target "rpi4" defaults to glibc, which isn't compatible with the binaries in the aarch64-musl rootfs. So the correct series of commands is:

./mkrootfs.sh aarch64-musl
./mkplatformfs.sh rpi4-musl void-aarch64-musl-ROOTFS-date.tar.xz
./mkimage.sh void-rpi4-musl-PLATFORMFS-date.tar.xz

**Comment by paper42** [comment]
This is not a bug, but a user error which should be documented - #126.
