### ISSUE TITLE
grub failed to install 

### ISSUE THREAD

**Issue by david-laine** [void-linux/void-mklive#223]
i tried void-mklive and i thought i may be missing some packages even though i installed grub on it it kept saying failed to install so i tried bulid-x86-images and the same thing happend

**Comment by abenson** [comment]
Can you provide more information on this?  What did you do?  Do you have output of the exact errors?

**Comment by kotoko** [comment]
Hi! I recently generated ISO using `void-mklive`. Generated does not have `grub` package installed. Could you double check that `grub` package is added to ISO?

**Comment by Vaelatern** [comment]
kotoko, please use the built in capabilities within mklive to specify what packages you want to install.

**Comment by kotoko** [comment]
Sure. Could you provide a list of packages that are required for `void-installer` to successfully install void? I will all pass them to the parameter `-p`. I don't want to waste too much time figuring it out myself.

**Comment by Vaelatern** [comment]
I'd love to provide them. Unfortunately they are already provided in various sample invocations and I don't want to waste my time finding them.

**Comment by kotoko** [comment]
You could at least post link to them...

Anyway I'm not sure that @Vaelatern understands that current version of mklive produces broken ISO. I generated ISO and got image without grub (installation fails at installing bootloader). @david-laine said that he generated ISO and also had missing grub. He then installed grub and said that after that installation also failed. I'm not sure why @Vaelatern  prefers to say on what activities he does not want to waste time instead of looking into this bug/regression.

**Comment by kotoko** [comment]
OK. Good to know. I managed to generate working ISO. Thank you!

**Comment by paper42** [comment]
This is most likely a user error, @david-laine if you believe this is a bug, please provide more information and reopen this issue.
