### ISSUE TITLE
Remove LXDM from most images

### ISSUE THREAD

**Issue by CameronNemo** [void-linux/void-mklive#271]
LXDM and LXDE are practically abandonware at this point. Unfortunately many of Void's non-LXDE images are using LXDE.

I propose the following changes:

* for lxqt, use SDDM in place of LXDM
* for mate, cinnnamon, and XFCE use LightDM with the basic gtk3 lightdm greeter

Edit: maldridge expressed displeasure with depending on LightDM, so this proposal is now SDDM for all the above listed images.

**Comment by Vaelatern** [comment]
We don't build new LXDE desktops, only XFCE and non-Xorg images (for the official images at least)

**Comment by paper42** [comment]
> We don't build new LXDE desktops, only XFCE and non-Xorg images (for the official images at least)

The main change would be a DM for Xfce because it currently still uses LXDM. We also still offer a script to build all variants, some of them work better than others.

What would you think about [greetd](https://git.sr.ht/~kennylevinsen/greetd)? From my testing it seems to be straightforward and we could easily have different greeters for different DEs if we wanted to.

**Comment by TrueTechie** [comment]
> > We don't build new LXDE desktops, only XFCE and non-Xorg images (for the official images at least)
> 
> The main change would be a DM for Xfce because it currently still uses LXDM. We also still offer a script to build all variants, some of them work better than others.
> 
> What would you think about [greetd](https://git.sr.ht/~kennylevinsen/greetd)? From my testing it seems to be straightforward and we could easily have different greeters for different DEs if we wanted to.

The only greeter for `greetd` in the repos is `tuigreet`. `gtkgreet` would fit Xfce if it were packaged.
