### ISSUE TITLE
Can you make a way to disable the binary blobs in the kernel?

### ISSUE THREAD

**Issue by FrostKnight** [void-linux/void-mklive#57]
I know that the linux kernel has binary blobs loaded regardless if you need them, I wondered if it would be possible, to make an easy option in the linux kernel to disable them if you don't need them.  I know you rejected another line of kernels, would you be willing to do this instead?
I only ask, because some computers can run without the binary blobs just fine and the binary blobs are a security risk.

**Comment by the-maldridge** [comment]
If you have a legitimate security report w.r.t. blobs available from the kernel archive, you should report it to the kernel security team rather than an independent distribution.

As far as making this an option for Void, that lies beyond the supported goals of the project, and certainly beyond the goals of mklive since it would involve making changes that are outside the package manager.  My suggestion to you would be to 1) alter a system to your liking after installation and 2) contribute to XBPS to help fix the situation with virtual packages, after which you could simply install without the firmware packages.

**Comment by FrostKnight** [comment]
So essentially you won't do what debian does in that sense of make it optionally on or off.  You do realize all binary blobs are security risks right? 
Please don't be elitist, that's why people hate archlinux.  I expected better from you guys, welp, guess I am never using your operating system again.   :/
PS, I know you guys are lying to my face. So don't pretend, ban me from here if you want, but I disagree on a very high level with your awful reasoning.

**Comment by the-maldridge** [comment]
For anyone else who comes across this and wants to fix it.  This isn't really possible to do with xbps as it currently stands.  The virtual packages system needs to be fixed, and then the situation with how we abuse metapackages needs to be fixed after that.  These are both long standing bugs in XBPS, so if you are a talented C programmer and want to help us out on this, please contact the team in IRC.

**Comment by Vaelatern** [comment]
@FrostKnight, you are welcome to come to #voidlinux in IRC and discuss further, but this issue is not the place to do it.
