### ISSUE TITLE
polkit: Local installation leaves dangling rules file.

### ISSUE THREAD

**Issue by espectalll** [void-linux/void-mklive#69]
Recently I noticed using my Void installation that I was able to run `pkexec -u root` without a password being required. After some digging in, I found out that `void-live.rules` is present in my system and not associated with any package. This means that, after installing Void (I don't remember how I did it, if I did so with the online or offline method, but if I had to bet it would be the latter), a file that allows unlimited full password-less root access for wheel accounts is silently left as part of the new system. 

Here's a demonstration of how it looks like on my system:

![Screenshot showing how `/etc/polkit-1/rules.d/void-live.rules` exists on my Void instalation and contains code that automatically allows root access without a password](https://user-images.githubusercontent.com/2456419/57981558-6eefca80-7a28-11e9-9636-a65ef6a177c7.png)

**Comment by espectalll** [comment]
The vulnerability was seemingly introduced here https://github.com/void-linux/void-mklive/commit/699937efcac563a57e56d07c3d4976999b7cc90b#diff-1549e771cc8a600c54842d0256eb8080

To fix the issue, all that is required is to make sure that the file isn't copied over a new Void installation. For current ones, please make sure you don't have it (and to remove it if you do) by doing `sudo rm /etc/polkit-1/rules.d/void-live.rules`

**Comment by Johnnynator** [comment]
Related: https://github.com/void-linux/void-mklive/pull/2

**Comment by espectalll** [comment]
Yeah, it may be fixed already by #2. However, if it is, existing installations haven't been patched properly.

**Comment by Johnnynator** [comment]
@espectalll That PR never was merged and therefore the issue never resolved. I just linked it as a reference

**Comment by Piraty** [comment]
Hmm i don't consider this per se an issue, as it is present since 2013 (699937efcac563a57e56d07c3d4976999b7cc90b), and it's a setting for convenient configuration of the live system providing a desktop environment (i think of wifi for example).
I think the issue is more about lacking documentation about what the "local" installation method actually does (i think it's at least somewhere mentioned on the main website).
As usual, it's a tradeoff: if it gets disabled by default, the live system will ask for the user's password upon some settings and everybody unable to "shutdown via buttons" after installation will seek for support as they's not aware of polkit and expect such things to "just work" (this already happens with users installing using "network" method, which of course does not ship such an "allow-all-for-wheel" polkit rule).

**Comment by espectalll** [comment]
@Piraty Under no circumstances should convenience be prioritized over unlimited access to full control of a system, and it should absolutely be considered as an issue per se. This is not a tradeoff that should be considered. In fact, it's not even a tradeoff - just make sure the file isn't copied over, or if it HAS to be, then delete it immediately after copying it. If it HAS to stay, then the whole installation process is wrong and should be discarded.

**Comment by mobinmob** [comment]
> @Piraty Under no circumstances should convenience be prioritized over unlimited access to full control of a system, and it should absolutely be considered as an issue per se. This is not a tradeoff that should be considered. In fact, it's not even a tradeoff - just make sure the file isn't copied over, or if it HAS to be, then delete it immediately after copying it. If it HAS to stay, then the whole installation process is wrong and should be discarded.

It is not just a matter of convenience, it a matter of polkit  configuration. See my [last comment](https://github.com/void-linux/void-mklive/pull/2#issuecomment-409025194) on the bug report and [this reddit thread.](https://www.reddit.com/r/voidlinux/comments/auk8pm/policykit_problems/) Removing void-live.rules is easy but it does not solve the problem of proper polkit configuration for the installed system.

**Comment by espectalll** [comment]
@mobinmob I wonder, is that solved? I certainly have no issues with GNOME. Regardless, it should a priority to remove that file over not disrupting the user interface since it's a critical vulnerability.

**Comment by mobinmob** [comment]
AFAICT it is not solved for DEs that use consolekit by default (mate, xfce etc). The need extra polkit rules. That is not unique to void, see the [desktop-priviledges package](https://aur.archlinux.org/packages/desktop-privileges/) on the aur.

**Comment by silvernode** [comment]
@mobinmob So let me get this straight; either many desktops are using polkit wrong or we should replace polkit because it's designed badly? I find this whole conversation very interesting and eye opening since this is the first time I have known of it.

**Comment by espectalll** [comment]
@mobinmob Then why not just provide the extra rules when installing ConsoleKit2?

**Comment by Vaelatern** [comment]
As I understand, it's only the local installation method, which essentially makes the OS on disk behave exactly like the live CD.

**Comment by mobinmob** [comment]
@silvernode The desktops I reffered to earlier are not using polkit wrong, the configuration of policykit when using the consolekit2 backend is imho not the best :) 

@espectalll These can be part of a solution, but the two rules attempt to solve only certain problems. Ι am not sure they are enough, or even the best approach possible. Anyway, this a security policy issue,  only the core team can decide on the solution.

**Comment by espectalll** [comment]
@Vaelatern Yeah, that's what I meant with "if I had to bet it would be the [offline installation method]"

@mobinmob For sure, I meant to apply __proper__ rules, not the current ones but only if you use ConsoleKit2.

**Comment by mobinmob** [comment]
> As I understand, it's only the local installation method, which essentially makes the OS on disk behave exactly like the live CD.

It is only the local installation method, if policykit and consolekit are present in the iso, so it does not affect the minimal iso.
https://github.com/void-linux/void-mklive/blob/40dd7a4ede3f217947311dc5742a5f73d30000d4/dracut/vmklive/adduser.sh#L38

**Comment by Piraty** [comment]
Well the thing here is that users are required to write their own polkit rules the way they want them to be, there's plenty of ways to setup policies for all kinds of stuff.
So far i'm not aware of any package in Void providing rule files for you that do what the mentioned file in the live system does. I don't know about other distros.
And i don't think Void should ship those.

I agree that installing this file is not ideal for unaware user, and i stumbled over this myself a few years ago.
I still assume the Installer is misleading, and most users prefer to install via "network" (i.e. do a miminal installation as you would do via chroot method) anyway because of aforementioned reasons.

**Comment by Vaelatern** [comment]
It would be best for our users to do a network install. The local install is only for those who like exactly what they see and do not want to spend time configuring further, or those who can not reach the network for some reason.

**Comment by CameronNemo** [comment]
@espectalll can you check the sudoers file? https://github.com/void-linux/void-mklive/blob/master/dracut/vmklive/adduser.sh#L35

**Comment by the-maldridge** [comment]
For folks reading along in the future.  Just to be clear this is intended behavior that's been known about for a long time.  Installing from the "Local" source copies the live squashfs onto the disk.  Its meant to get people going as quickly as possible and really is not the proper way to install the system.

Again, to be clear, this is not considered a security issue and I have changed the title of this issue to reflect that.  Additionally, since this is an issue with void-mklive and not void-packages, I have transferred the issue there.

When looking for security issues, responsible researchers are encouraged to reach out in private and preferably via PGP encrypted message rather than opening a globally visible GitHub issue.  Treating security disclosures otherwise is not only reckless and foolhardy, but also sets a bad example for other researchers.

**Comment by espectalll** [comment]
@CameronNemo Yeah, that added the following line into my setup

`anon ALL=(ALL) NOPASSWD: ALL`

...great, another security hole. "At least" this one is rather unlikely because you have to exploit it on an account that matches the username with the `$USERNAME` assigned for the Void installer - in this case, `anon`.

@the-maldridge Is "shipping a massive critical vulnerability by default" intended behavior, which you didn't even intend to make people aware of? And yes, it's a vulnerability, just read the Wikipedia definition for it:

"_a vulnerability is a weakness which can be exploited by a threat actor, such as an attacker, to perform unauthorized actions within a computer system_"

This, in fact, is as vulnerable as a system gets, and it's just not the worst case scenario because it's only on wheel accounts and by default those are assigned passwords. And you're not even actively warning people about it, just assuming people will check and change security settings on their own instead of shipping sane defaults, which is mind boggling to me.

I agree that other channels should be used, for which I was not made aware of their availability. I just recurred to whatever I knew of, since it was urgent. Void should have at the very least advisory channels, security bug trackers and security contact mails, if not a formal security group as well. But do you really care about security enough?

**Comment by mobinmob** [comment]
@CameronNemo The relevant lines from the installer:
 https://github.com/void-linux/void-mklive/blob/40dd7a4ede3f217947311dc5742a5f73d30000d4/installer.sh.in#L1301-L1313

Maybe the best way to solve the problem is to remove void-line.rules from the installation and have something in the void-docs that indicates that  users should build their own polkit rules, with examples for the most common cases?

**Comment by mobinmob** [comment]
@the-maldridge If installing from "local" source is not "really the proper way to install the system" then it should either be clearly indicated as such or the option removed from the installer entirely. I'd rather have it fixed - void-installer has its problems, but the local installation is a fast and reliable way to have a rather complete system.

**Comment by Vaelatern** [comment]
I kind of like the solution (thanks @CameronNemo) where we have a specific package that provides the live-iso files, like this one. Then, as part of the local installation, we could just warn people to uninstall the package.

**Comment by Duncaen** [comment]
We could just remove files intended only for the live system (like we already to with `/etc/motd` and other files).
If a user doesn't like that they get asked for a password for privileged actions, they either install consolekit, elogind or recreate a similar rule.

**Comment by CameronNemo** [comment]
I had in mind that we could remove the files by removing the package that provides them. Easier than managing them manually.

**Comment by q66** [comment]
Why not just keep the polkit rule where it is, but adjust it to do more fine-grained "correct" rules, like

```
polkit.addRule(function(action, subject) {
    if (action.id == "org.freedesktop.upower.hibernate" ||
        action.id == "org.freedesktop.upower.suspend") {
        return polkit.Result.YES;
    } else if ((
        action.id.indexOf("org.freedesktop.udisks2.") == 0 ||
        action.id.indexOf("org.freedesktop.udisks.") == 0
    ) && subject.isInGroup("storage")) {
        return polkit.Result.YES;
    }
});
```

Then things can keep working, and everyone can be happy

**Comment by Duncaen** [comment]
Would still be better if this is a file managed through xbps in case we need to change the rules.
There shouldn't be any untracked files, just because you installed from a desktop ISO with local as installation source.

**Comment by q66** [comment]
yeah, obviously having a package for "desktop" polkit rules and have it be installed together with the respective desktops sounds like the best approach

**Comment by Vaelatern** [comment]
@CameronNemo would you be willing to put together a pair of pull requests, one here and one on void-packages, to solve this?

**Comment by Vaelatern** [comment]
Ok, original author has officially crossed into unacceptable territory with this response. This issue has been handled in some fashion, and will be improved upon in the future.

The original author has shown exceptionally bad faith (if this is a zero day, then you do not just come to github then reddit to yap about it), then chosen to smear "this is what Void thinks of security" all over public channels because a fix wasn't in within a day of posting.

Bad faith efforts will not be tolerated. And while the results of these efforts were positive, I do not see a reason to leave this issue open.

**Comment by espectalll** [comment]
@Vaelatern Sorry if you find my response unacceptable. Absolutely no bad faith was intended. I considered this to be the proper response to force awareness and accountability in order to achieve organizational/structural changes in the project (such changes being those required to have proper, formal ways to deal with security issues), and not a way of personally attacking anyone on the project.

I agree with closing down the ticket, this particular issue seems to be getting solved. I ask you, however, to take the steps that I did all of this for. And I do it with all of the good faith and intent I have, and with no will to harm. I agree, finally, that bad faith efforts must and should not be tolerated, and so I hope they are.

**Comment by rubyFeedback** [comment]
> Sorry if you find my response unacceptable.

I don't think it is the response but the underlying premise before that.

For example, a LiveCD/DVD system should not impede the user who wants to install something.

After the installation, though, it may indeed be annoying for users to find random superuser-accounts.

But either way I think this is a really small issue - the simplest change could be to add a checkbox for the installer, e. g. to remove any unwanted superuser accounts after the installation has finished.

For the record, I disagree with Piraty stating that "And i don't think Void should ship those." - the thing is that Void already ships with a certain set of udev rules. This may not necessarily be what the user wants to have, so why is the user forced to auto-accept these, anyway?

A more elegant long-term solution may be to just pick a few profiles, e. g. one could be for convenience (so less restriction), one for server systems, one for security (highest restrictions) etc... 

With just a few profiles this could be solved elegantly and indirectly.

**Comment by silvernode** [comment]
I agree that we need a package, and that package includes sane polkit rules. In the future I would like to see and possibly participate in a new installer all together. We should discuss this at length (somewhere else) until everyone is happy with the blueprint of features etc. In short, a simple setup option will automatically install sane polkit rules for an average user while advanced will warn and give the option to keep the live rules but fallback on sane ones. Oh and let's keep using ncurses dialogs. :)

**Comment by Piraty** [comment]
For reference: addressed with https://github.com/void-linux/void-packages/commit/3ff003af44ab91fb4c1d7fcc91776ef4693a2253
