### ISSUE TITLE
Can livenet Dracut module be included in the distributed Live ISO initrd? 

### ISSUE THREAD

**Issue by thelamer** [void-linux/void-mklive#97]
Currently when trying to boot the Live ISO components from an http/https endpoint you get back : 
```
dracut: FATAL: Don't know how to handle 'root=live:http........
```

Basic `/etc/dracut.conf` to add this: (on top of your hooks)
```
add_dracutmodules+="dmsquash-live livenet nfs network base"
show_modules=yes
hostonly="no"
```
This is a stock module: 
https://github.com/dracutdevs/dracut/tree/master/modules.d/90livenet

To also provide ssl support the host would need `ca-certificates` installed. 

I am currently working through live distros to include in https://netboot.xyz/ menus. 
Normally I would generate the vmlinuz/initrd combo in Docker, and maybe you could help me there. Due to the rolling nature of the distro I am not capable (I think) of installing the precise kernel version used in the already built Live CDs.

I am OK with maintaining a fork of the initrd/vmlinuz stuff, just figured I would ping you to see if this is something that could be added by default.

**Comment by the-maldridge** [comment]
There's nothing special about the initrd that void provides, so you could build your own.  I don't think the modules matter for the live images either because there shouldn't be any proprietary modules loading.

You could make a patch to the generate_initramfs function in mklive.sh to add whatever modules you want, or you could just extract the squashfs and boot that directly on a vanilla kernel.

**Comment by thelamer** [comment]
Thanks for the reply, but there is actually a ton of modules in both the initrd and squashfs :
initrd `/usr/lib/modules/VERSION/kernel`
squash `/run/rootfsbase/usr/lib/modules/VERSION/kernel`

Barely anything is flagged to compile in the Kernel so basic stuff like USB storage would not work with a mismatched kernel/initrd/squash combo. 
The main point of booting these ISOs off the internet is to be as close to the local ISO experience as possible.

As far as me building exact kernel/initrd combos as I stated earlier I am not sure I can do that unless you have some kind of snapshots repo I can roll back in time with like Debian. 
The current iso has 4.18.17_1 installed with embedded modules though the closest to that in the current packages is `linux4.19-4.1986_1`. 

I am not super comfortable with building the full distro also, part of the trust in people booting stuff off the internet is them being able to see we just download your ISO rip it apart and upload it to a new endpoint in a transparent manner with the ability to md5 both the source and destination. There is also again the concept that they are booting the same stuff as others using local medium and should expect the same results.

**Comment by thelamer** [comment]
I just wanted to give some update to this as I tried to layer in dracut scripts manually with some success though it is dirty. 

I noticed that you are already embedding a full CA certificates package in the initramfs on top of that `dracut-network` includes all these scripts to embed with module add options, the curl bin does not stack on too much on top of this , to add this the code changes that would need to be made before building the initrd would be: 
```
echo 'add_dracutmodules+="dmsquash-live livenet"' > /usr/lib/dracut/dracut.conf.d/11-livenet-void.conf
```
And the addition of curl here: 
https://github.com/void-linux/void-mklive/blob/510a4bebd16c90a3b7cdd15ba6bc22331d92e7ea/mklive.sh.in#L33

**Comment by the-maldridge** [comment]
Seems reasonable, but as this is something that Void as a project has no intent of supporting in any way, shape, or form, its something that will be discussed on IRC for some second opinions.

**Comment by Vaelatern** [comment]
Perhaps this is something that would better be a fit for a documentation page, as a possible thing users may want to do.

**Comment by xtraeme** [comment]
I agree. You can build your custom image via void-mklive.

**Comment by thelamer** [comment]
As stated earlier , our intent as a project is to make minimal modifications to upstream live CDs so users can boot their favorite distros .

I understand if your project does not want to embed these hooks and the curl bins/libs in your initramfs, but we do not want to build custom distros that fork from your environment in versioning numbers and dates. 
I know it is not apples to apples especially because of the rolling nature of your distro, but when people want to boot a Bionic CD they don't want to boot netbootxyz-custom-01022020 they want to boot and install 18.04.3. 

Thanks for the consideration, but if documentation is your team's decision please feel free to close this one out and no hard feelings, just reaching out to see if it was something you are interested in supporting.

**Comment by Vaelatern** [comment]
I think the hangup is that this would be the first modification we would make to our live images not for the sake of our users, but for the sake of compatibility with an external project.

**Comment by the-maldridge** [comment]
That really is my main sticking point.  You're doing something with images that really isn't something I have any intent of supporting as an upstream maintainer, and I can't really imagine many of our other maintainers are interested in supporting it either.

Part of our reason for providing the mklive toolkit as a ready to run system is to enable unsupported use cases beyond our source tree.  There is nothing stopping you from compiling your own images and enabling this feature for your users.

Void though has an interest in security, a large part of which means that you get the ISO directly from one of our mirrors and check it against our keys.  Booting from some 3rd party means that that chain of trust is broken.   You should also be aware that our ISOs are only rebuilt every 6 months  at the most frequent.  We regularly let them grow quite old because once installed (which is their singular function) the system can be updated without issue.

I'm going to go ahead and close this out that the Void project isn't interested in supporting this use case right now, but we'll be sure to reach out if this stance changes in the future.
